mysite/apps/login/urls.py
from django.urls import path
from . import views
app_name = 'login'

urlpatterns = [
    path('', views.mainlogin, name='mainlogin'),
    path('desconectar', views.logout_home, name='logout'),
    path('registro', views.RegistroUsuario, name='registro'),
]

mysite/apps/mainpage/urls.py
from django.urls import path
from . import views

app_name = 'mainpage'

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('añadir/', views.add, name='añadir'),
    path('añadir_nota/', views.add_note, name='añadir nota'),
    # rutas del buscador de la API
    path('buscar/', views.fetch, name='buscar'),
    path('save/<str:pk>', views.save_fetch, name='save'),
    # rutas de las series
    path('delete_serie/<int:pk>', views.delete_serie, name='eliminar serie'),
    path('edit_serie/<int:pk>', views.edit_serie, name='editar serie'),
    # rutas de las peliculas
    path('delete_film/<int:pk>', views.delete_film, name='eliminar pelicula'),
    path('edit_film/<int:pk>', views.edit_film, name='editar pelicula'),
    # rutas del perfil
    path('perfil/', views.perfil, name='perfil'),
    path('cambiar_user/', views.change_username, name='cambiar user'),
    path('cambiar_password/', views.change_password, name='update password'),
    path('cambiar_imagen/', views.set_image, name='set image'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from django.urls import path, include, re_path

urlpatterns = [
    path('', include('apps.mainpage.urls'), name='inicio'),
    path('admin/', admin.site.urls),
    path('login/', include('apps.login.urls'), name='login'),
    path('reset/password_reset', PasswordResetView.as_view(template_name='password/password_reset_form.html',
         email_template_name="password/password_reset_email.html"),
         name='password_reset'),
    path('reset/password_reset_done',
         PasswordResetDoneView.as_view(template_name='password/password_reset_done.html'),
         name='password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-za-z_\-]+)/(?P<token>.+)/$',
            PasswordResetConfirmView.as_view(template_name='password/password_reset_confirms.html'),
            name='password_reset_confirm'),
    path('reset/done', PasswordResetCompleteView.as_view(template_name='password/password_reset_complete.html'),
         name='password_reset_complete'),
]

mysite/apps/login/models.py
from django.contrib.auth.models import User


# la base de datos de usuarios viene dada por django

mysite/apps/login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, ReadOnlyPasswordHashField
from django.contrib.auth.forms import AuthenticationForm, UsernameField
from django.contrib.auth.models import User


class CustomUserCreationForm(UserCreationForm):
    username = UsernameField(
        widget=forms.TextInput(attrs={'class': 'input', 'autofocus': True,
                                      'placeholder': 'Nombre de Usuario (lo usarás para iniciar sesión)'})
    )
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'input', 'autofocus': True, 'placeholder': 'Nombre'})
    )
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'input', 'autofocus': True, 'placeholder': 'Apellidos'})
    )
    email = forms.EmailField(
        widget=forms.TextInput(attrs={'class': 'input', 'autofocus': True, 'placeholder': 'Email'})
    )
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input', 'placeholder': 'Contraseña'}))
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'input', 'placeholder': 'Confirmar Contraseña'}))

    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email", "password1", "password2"]


class UserChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    disabled password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class UsernameForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    disabled password hash display field.
    """
    class Meta:
        model = User
        fields = ('username',)


class LoginForm(AuthenticationForm):
    username = UsernameField(
        widget=forms.TextInput(attrs={'class': 'input', 'autofocus': True, 'placeholder': 'Nombre de Usuario'})
    )
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input', 'placeholder': 'Contraseña'}))


class AddSerie(forms.Form):
    name = forms.CharField(
        widget=forms.TextInput(attrs={'required': 'True', 'class': 'input', 'placeholder': 'Título'}))

    season = forms.IntegerField(
        widget=forms.TextInput(attrs={'class': 'input', 'placeholder': 'Temporada'}))

    chapter = forms.IntegerField(
        widget=forms.TextInput(attrs={'class': 'input', 'placeholder': 'Capítulo'}))

    image = forms.ImageField(required=False)


class AddFilm(forms.Form):
    name = forms.CharField(
        widget=forms.TextInput(attrs={'required': 'True', 'class': 'input', 'placeholder': 'Título'}))

    time = forms.CharField(
        widget=forms.TextInput(attrs={'required': 'True', 'class': 'input', 'placeholder': '01:45:50'}))

    image = forms.ImageField(required=False)


class NewNote(forms.Form):
    id_nota = forms.IntegerField()
    type_nota = forms.CharField()
    nota_text = forms.CharField()


class NewImage(forms.Form):
    image = forms.ImageField()

mysite/apps/login/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render
from django.http import HttpResponseRedirect

# Create your views here.
from django.urls import reverse
from .forms import CustomUserCreationForm, LoginForm


def mainlogin(request):
    data = {
        'form': LoginForm(),
    }
    if request.method == 'POST':
        formulario = LoginForm(data=request.POST)
        if formulario.is_valid():
            user = authenticate(username=formulario.cleaned_data['username'],
                                password=formulario.cleaned_data['password'])
            login(request, user)
            return HttpResponseRedirect(reverse('mainpage:inicio'))
        else:
            messages.error(request, 'Usuario o contraseña incorrectos.')
    return render(request, 'login/login.html', data)


# parece que funciona
def logout_home(request):
    logout(request)
    return HttpResponseRedirect(reverse('login:mainlogin'))


def RegistroUsuario(request):
    data = {
        'form': CustomUserCreationForm(),
    }
    if request.method == 'POST':

        formulario = CustomUserCreationForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            user = authenticate(username=formulario.cleaned_data['username'],
                                password=formulario.cleaned_data['password1'])
            login(request, user)
            return HttpResponseRedirect(reverse('mainpage:inicio'))
        data['form'] = formulario
    return render(request, 'login/registro.html', data)

mysite/templates/login/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bulma.css' %}">
    <link href="{% static 'css/base.css' %}" rel="stylesheet" type="text/css">
    <script src="{% static 'js/Navbar.js' %}"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
</head>

{% block heading %}


{% endblock %}

<body>
<nav class="navbar">
    <div class="navbar-brand">
        <a href="{% url 'mainpage:inicio'%}" style="margin: 5px !important;">
            <img alt="logo" src="/static/media/LogoAleAPrisa.png" height="60px" style="height: 60px !important">
            <img alt="logo" src="/static/media/playdino.png" height="50px" style="height: 50px !important">
        </a>
        <div class="navbar-burger burger" data-target="nav-data">
            <span></span>
            <span></span>
            <span></span>
        </div>
    </div>
        <div class="navbar-menu" id="nav-data">
            <div class="navbar-end">
                <div class="navbar-item">
                    <div class="field is-grouped">
                        <p class="control">
                            <a href="{% url 'login:mainlogin' %}" class="button is-primary">
                                <span>INICIAR SESION</span>
                            </a>
                             <a href="{% url 'login:registro' %}" class="button is-primary">
                                <span>REGISTRATE</span>
                            </a>
                        </p>
                    </div>
                </div>
        </div>
    </div>

</nav>

{% block content %}

{% endblock %}

<footer class="footer">
    <div class="columns" style="width: 90%; margin:0 5% 0">
      <div class="column">
            <img src="/static/media/LogoAleAPrisa.png" alt="LOGO" height="150px" style="height: 150px !important">
            <img alt="logo" src="/static/media/playdino.png" style="width: 224px !important">
          <p></p>
      </div>
      <div class="column">
          <h6 class="is-size-6"><strong>DOCUMENTACIÓN</strong></h6>
          <p><a href="https://bulma.io" target="_blank"><i class="fas fa-file-code"></i>&nbsp;Bulma</a></p>
          <p><a href="https://github.com" target="_blank"><i class="fab fa-github"></i>&nbsp;Github</a></p>
          <p><a href="https://djangoproject.com" target="_blank"><i class="fab fa-python"></i>&nbsp;Django</a></p>
          <p><a href="https://fontawesome.com" target="_blank"><i class="fas fa-flag"></i>&nbsp;Font Awesome 5</a></p>
          <p><a href="/static/media/Manual.pdf" download="ManualPlayDino"><i class="fas fa-file-pdf"></i>&nbsp;Manual de usuario</a></p>
      </div>
      <div class="column">
          <h6 class="is-size-6"><strong>¿DÓNDE PUEDO VER MIS SERIES?</strong></h6>
          <div class="columns">
              <div class="column">
                  <p><a href="https://hbo.com" target="_blank" style="color: #0008a3">&nbsp;HBO</a></p>
                  <p><a href="https://primevideo.com" target="_blank" style="color:#003ca3">&nbsp;Prime Video</a></p>
                  <p><a href="https://disneyplus.com" target="_blank" style="color:#006aa3">&nbsp;Disney+</a></p>
                  <p><a href="https://ver.movistarplus.es/" target="_blank" style="color: #87d9fa">&nbsp;Movistar+</a></p>
              </div>
              <div class="column">
                  <p><a href="https://rakuten.es" target="_blank" style="color: #8a0000">&nbsp;Rakuten TV</a></p>
                  <p><a href="https://netflix.com" target="_blank" style="color: red">&nbsp;Netflix</a>
                  <p><a href="https://tv.apple.com" target="_blank" style="color:orangered">&nbsp;Apple TV</a></p>
                  </p><p><a href="https://crunchyroll.com" target="_blank" style="color: orange">&nbsp;Crunchyroll</a></p>
              </div>
          </div>
      </div>
    </div>
</footer>

</body>
</html>

mysite/templates/login/login.html
{% extends 'login/base.html' %}
{% block title %}
    BIENVENIDO
{% endblock %}

{% block content %}
    {% if messages %}
        {% for message in messages %}
            <div class="message1" style="z-index: 1; position: relative">
            <article class="message is-danger is-inverted">
                 <div class="message-body">{{ message }}</div>
             </article></div>
         {% endfor %}
    {% endif %}

    <div class="container">
        <div class="columns is-mobile" >
            <div class="column is-half is-offset-one-quarter" style="margin-top: 150px; margin-bottom: 150px">
                <h3 class="title is-size-3">INICIAR SESION</h3>
                 <form  method="post">
                    {% csrf_token %}
                    {% for non_field_error in form.non_field_errors %}
                        <p class="help is-danger">{{ non_field_error }}</p>
                    {% endfor %}
                    {% for field in form %}
                        <div class="field" >
                            {{ field }}
                        {% for error in field.errors %}
                            <p class="help is-danger">{{ error }}</p>
                        {% endfor %}
                        </div>
                    {% endfor %}
                    <button type="submit" class="button is-primary is-fullwidth" style="margin-bottom: 5px">INICIAR SESION</button>
                    <a href="{% url 'password_reset' %}"><label>¿Has olvidado tu contraseña?</label></a>
                </form>

            </div>
        </div>
    </div>

{% endblock %}

mysite/templates/login/registro.html
{% extends 'login/base.html' %}
{% block title %}
    REGISTRO
{% endblock %}

{% block content %}
    <div class="container">
        <div class="columns is-mobile">
            <div class="column is-half is-offset-one-quarter" style="margin-top: 50px;margin-bottom: 50px; text-align: center">
                <h3 class="title is-size-3" >REGISTRATE</h3>
                <h4 class="tittle is-size-5">INTRODUCE LOS SIGUIENTES DATOS</h4>
                <br/>
                 <form  method="post">
                    {% csrf_token %}
                    {% for non_field_error in form.non_field_errors %}
                        <p class="help is-danger">{{ non_field_error }}</p>
                    {% endfor %}
                        <label style="font-size: 12px">Un consejo: pon el Nombre de Usuario en minúsculas ya que
                            para iniciar sesión deberás introducirlo exactamente igual </label>
                    {% for field in form %}
                        <div class="field">
                            <label for="{{ field.id_for_label }}" class="label"></label>
                            {{ field }}
                        {% for error in field.errors %}
                            <p class="help is-danger">{{ error }}</p>
                        {% endfor %}
                        </div>
                    {% endfor %}
                    <button type="submit" class="button is-primary is-large is-fullwidth">REGISTRARME</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}