mysite/apps/login/urls.py
from django.urls import path
from . import views
app_name = 'login'

urlpatterns = [
    path('', views.mainlogin, name='mainlogin'),
    path('desconectar', views.logout_home, name='logout'),
    path('registro', views.RegistroUsuario, name='registro'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from django.urls import path, include, re_path

urlpatterns = [
    path('', include('apps.mainpage.urls'), name='inicio'),
    path('admin/', admin.site.urls),
    path('login/', include('apps.login.urls'), name='login'),
    path('reset/password_reset', PasswordResetView.as_view(template_name='password/password_reset_form.html',
         email_template_name="password/password_reset_email.html"),
         name='password_reset'),
    path('reset/password_reset_done',
         PasswordResetDoneView.as_view(template_name='password/password_reset_done.html'),
         name='password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-za-z_\-]+)/(?P<token>.+)/$',
            PasswordResetConfirmView.as_view(template_name='password/password_reset_confirms.html'),
            name='password_reset_confirm'),
    path('reset/done', PasswordResetCompleteView.as_view(template_name='password/password_reset_complete.html'),
         name='password_reset_complete'),
]

mysite/apps/login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, ReadOnlyPasswordHashField
from django.contrib.auth.forms import AuthenticationForm, UsernameField
from django.contrib.auth.models import User


class CustomUserCreationForm(UserCreationForm):
    username = UsernameField(
        widget=forms.TextInput(attrs={'class': 'input', 'autofocus': True,
                                      'placeholder': 'Nombre de Usuario (lo usarás para iniciar sesión)'})
    )
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'input', 'autofocus': True, 'placeholder': 'Nombre'})
    )
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'input', 'autofocus': True, 'placeholder': 'Apellidos'})
    )
    email = forms.EmailField(
        widget=forms.TextInput(attrs={'class': 'input', 'autofocus': True, 'placeholder': 'Email'})
    )
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input', 'placeholder': 'Contraseña'}))
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'input', 'placeholder': 'Confirmar Contraseña'}))

    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email", "password1", "password2"]


class UserChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    disabled password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class UsernameForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    disabled password hash display field.
    """
    class Meta:
        model = User
        fields = ('username',)


class LoginForm(AuthenticationForm):
    username = UsernameField(
        widget=forms.TextInput(attrs={'class': 'input', 'autofocus': True, 'placeholder': 'Nombre de Usuario'})
    )
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input', 'placeholder': 'Contraseña'}))


class AddSerie(forms.Form):
    name = forms.CharField(
        widget=forms.TextInput(attrs={'required': 'True', 'class': 'input', 'placeholder': 'Título'}))

    season = forms.IntegerField(
        widget=forms.TextInput(attrs={'class': 'input', 'placeholder': 'Temporada'}))

    chapter = forms.IntegerField(
        widget=forms.TextInput(attrs={'class': 'input', 'placeholder': 'Capítulo'}))

    image = forms.ImageField(required=False)


class AddFilm(forms.Form):
    name = forms.CharField(
        widget=forms.TextInput(attrs={'required': 'True', 'class': 'input', 'placeholder': 'Título'}))

    time = forms.CharField(
        widget=forms.TextInput(attrs={'required': 'True', 'class': 'input', 'placeholder': '01:45:50'}))

    image = forms.ImageField(required=False)


class NewNote(forms.Form):
    id_nota = forms.IntegerField()
    type_nota = forms.CharField()
    nota_text = forms.CharField()


class NewImage(forms.Form):
    image = forms.ImageField()

mysite/templates/password/password_reset_complete.html
{% extends 'login/base.html' %}

{% block content %}
    <h4 class="title is-size-4" style="margin-top: 200px; text-align: center">
        Su contraseña fue restablecida con éxito.</h4>

    <p class="has-text-centered"><a class="button is-primary is-rounded" href="{% url 'login:mainlogin' %}">
        Iniciar Sesión</a></p>

{% endblock %}

mysite/templates/password/password_reset_confirms.html
{% extends 'login/base.html' %}
{% block content %}
    {% if validlink %}

    <h4 class="title is-size-4" style="margin-top: 200px; text-align: center">
        Nueva contraseña
    </h4>

    <form method="post">
    {% csrf_token %}

    {{ form.new_password1.errors }}
    <label for="id_new_password1">Nueva Contraseña: &nbsp;</label>
    {{ form.new_password1 }}

    {{ form.new_password2.errors }}
    <label for="id_new_password2">Confirme Contraseña: &nbsp;</label>
    {{ form.new_password2 }}
    <input type="submit" value="Cambiar mi Contraseña">
    </form>

    {% else %}
    <h4 class="title is-size-4" style="margin-top: 200px; text-align: center">
        ENLACE INVÁLIDO: ESTE ENLACE YA HA SIDO UTILIZADO
    </h4>

    {% endif %}

{% endblock %}

mysite/templates/password/password_reset_done.html
{% extends 'login/base.html' %}
{% block content %}

    <h4 class="title is-size-4" style="margin-top: 200px; text-align: center">
        Te hemos enviado un correo con un enlace para restablecer tu contraseña</h4>
{% endblock %}

mysite/templates/password/password_reset_email.html
Solicitaste restablecer tu contraseña
Haz click en el siguiente link para establecer una nueva contraseña.
{% block reset_link %}
    {{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token%}
{% endblock %}
Tu nombre de usuario es: {{ user.get_username }}

mysite/templates/password/password_reset_form.html
{% extends 'login/base.html' %}
{% block content %}
    <div class="container">
        <div class="columns is-mobile" >
            <div class="column is-half is-offset-one-quarter" style="margin-top: 200px; margin-bottom: 200px; text-align: center">
                <h3 class="title is-size-3">Recuperar contraseña</h3>
                <form method="post">
                {% csrf_token %}
                <label class= 'field' for="id_email"> Introduce tu email: &nbsp;</label>{{ form.email }}
                <input style="margin-top:5%; width: 80%" class="button is-primary is-rounded"
                              type="submit" value="Enviar"/>
                </form>
            </div>
        </div>
    </div>

{% endblock %}