mysite/apps/login/urls.py
from django.urls import path
from . import views
app_name = 'login'

urlpatterns = [
    path('', views.mainlogin, name='mainlogin'),
    path('desconectar', views.logout_home, name='logout'),
    path('registro', views.RegistroUsuario, name='registro'),
]

mysite/apps/mainpage/urls.py
from django.urls import path
from . import views

app_name = 'mainpage'

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('añadir/', views.add, name='añadir'),
    path('añadir_nota/', views.add_note, name='añadir nota'),
    # rutas del buscador de la API
    path('buscar/', views.fetch, name='buscar'),
    path('save/<str:pk>', views.save_fetch, name='save'),
    # rutas de las series
    path('delete_serie/<int:pk>', views.delete_serie, name='eliminar serie'),
    path('edit_serie/<int:pk>', views.edit_serie, name='editar serie'),
    # rutas de las peliculas
    path('delete_film/<int:pk>', views.delete_film, name='eliminar pelicula'),
    path('edit_film/<int:pk>', views.edit_film, name='editar pelicula'),
    # rutas del perfil
    path('perfil/', views.perfil, name='perfil'),
    path('cambiar_user/', views.change_username, name='cambiar user'),
    path('cambiar_password/', views.change_password, name='update password'),
    path('cambiar_imagen/', views.set_image, name='set image'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from django.urls import path, include, re_path

urlpatterns = [
    path('', include('apps.mainpage.urls'), name='inicio'),
    path('admin/', admin.site.urls),
    path('login/', include('apps.login.urls'), name='login'),
    path('reset/password_reset', PasswordResetView.as_view(template_name='password/password_reset_form.html',
         email_template_name="password/password_reset_email.html"),
         name='password_reset'),
    path('reset/password_reset_done',
         PasswordResetDoneView.as_view(template_name='password/password_reset_done.html'),
         name='password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-za-z_\-]+)/(?P<token>.+)/$',
            PasswordResetConfirmView.as_view(template_name='password/password_reset_confirms.html'),
            name='password_reset_confirm'),
    path('reset/done', PasswordResetCompleteView.as_view(template_name='password/password_reset_complete.html'),
         name='password_reset_complete'),
]

mysite/apps/mainpage/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.


class Permissions:
    EDIT_SERIES = 'Edit series'
    ADD_SERIES = 'Edit client'
    DELETE_SERIES = 'Delete Series'


class Series(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, to_field='id', on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=100)
    season = models.IntegerField(default=1)
    chapter = models.IntegerField(default=1)
    image = models.ImageField(upload_to='static/media/', default='default.png')
    nota = models.CharField(default="", max_length=500)

    def __str__(self):
        return self.name


class Films(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, to_field='id', on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=100)
    time = models.CharField(max_length=100, default="00:00:00")
    image = models.ImageField(upload_to='static/media/', default='default.png')
    nota = models.CharField(default="", max_length=500)

    def __str__(self):
        return self.name


class Fetch(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100)
    image = models.CharField(max_length=200)
    imdb = models.CharField(max_length=20, null=True)
    type = models.CharField(max_length=100)

    def __srt__(self):
        return self.title


# esta es la imagen de perfil de cada usuario
class Image(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, to_field='id', on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to='static/media/profile', default='default.png')

    def __srt__(self):
        return self.user

mysite/apps/login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, ReadOnlyPasswordHashField
from django.contrib.auth.forms import AuthenticationForm, UsernameField
from django.contrib.auth.models import User


class CustomUserCreationForm(UserCreationForm):
    username = UsernameField(
        widget=forms.TextInput(attrs={'class': 'input', 'autofocus': True,
                                      'placeholder': 'Nombre de Usuario (lo usarás para iniciar sesión)'})
    )
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'input', 'autofocus': True, 'placeholder': 'Nombre'})
    )
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'input', 'autofocus': True, 'placeholder': 'Apellidos'})
    )
    email = forms.EmailField(
        widget=forms.TextInput(attrs={'class': 'input', 'autofocus': True, 'placeholder': 'Email'})
    )
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input', 'placeholder': 'Contraseña'}))
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'input', 'placeholder': 'Confirmar Contraseña'}))

    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email", "password1", "password2"]


class UserChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    disabled password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class UsernameForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    disabled password hash display field.
    """
    class Meta:
        model = User
        fields = ('username',)


class LoginForm(AuthenticationForm):
    username = UsernameField(
        widget=forms.TextInput(attrs={'class': 'input', 'autofocus': True, 'placeholder': 'Nombre de Usuario'})
    )
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input', 'placeholder': 'Contraseña'}))


class AddSerie(forms.Form):
    name = forms.CharField(
        widget=forms.TextInput(attrs={'required': 'True', 'class': 'input', 'placeholder': 'Título'}))

    season = forms.IntegerField(
        widget=forms.TextInput(attrs={'class': 'input', 'placeholder': 'Temporada'}))

    chapter = forms.IntegerField(
        widget=forms.TextInput(attrs={'class': 'input', 'placeholder': 'Capítulo'}))

    image = forms.ImageField(required=False)


class AddFilm(forms.Form):
    name = forms.CharField(
        widget=forms.TextInput(attrs={'required': 'True', 'class': 'input', 'placeholder': 'Título'}))

    time = forms.CharField(
        widget=forms.TextInput(attrs={'required': 'True', 'class': 'input', 'placeholder': '01:45:50'}))

    image = forms.ImageField(required=False)


class NewNote(forms.Form):
    id_nota = forms.IntegerField()
    type_nota = forms.CharField()
    nota_text = forms.CharField()


class NewImage(forms.Form):
    image = forms.ImageField()

mysite/apps/mainpage/views.py
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from django.contrib.auth.forms import PasswordChangeForm
from .imdb import search, search_by_id
from .models import Series, Films, Fetch, Image
from apps.login.forms import AddSerie, AddFilm, UserChangeForm

# Create your views here.
from ..login.forms import NewNote, UsernameForm, NewImage


@login_required(login_url=reverse_lazy('login:mainlogin'))
def inicio(request):
    notas_form = NewNote()
    usuario = request.user
    series = Series.objects.filter(user=usuario)
    films = Films.objects.filter(user=usuario)
    context = {'series': series, 'films': films, 'form': notas_form}
    return render(request, 'mainpage/inicio.html', context)


@login_required(login_url=reverse_lazy('login:mainlogin'))
def perfil(request):
    usuario = request.user
    image = Image.objects.filter(user=usuario)
    user_form = UserChangeForm(instance=request.user)
    password_form = PasswordChangeForm(request.user)
    if image.exists():
        ctx = {
            'usuario': usuario,
            'image': Image.objects.get(user=usuario),
            'form': user_form,
            'password_form': password_form
        }
    else:
        ctx = {
            'usuario': usuario,
            'form': user_form,
            'password_form': password_form
        }
    if request.method == 'POST':
        form = UserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'CAMPO(S) MODIFICADOS CON ÉXITO')
            return redirect(to='mainpage:perfil')
    return render(request, 'mainpage/perfil.html', ctx)


@login_required(login_url=reverse_lazy('login:mainlogin'))
def add(request):
    data = {
        'Serieform': AddSerie(),
        'Filmform': AddFilm()
    }
    if request.method == 'POST':
        formulary1 = AddFilm(request.POST, request.FILES)
        if formulary1.is_valid():
            nueva_peli = Films(
                name=formulary1.cleaned_data['name'],
                time=formulary1.cleaned_data['time'],
                user=request.user,
                image=formulary1.cleaned_data['image'],
            )
            nueva_peli.save()
            messages.success(request, 'Añadido con éxito')
            return redirect(to='mainpage:inicio')

        formulary2 = AddSerie(request.POST, request.FILES)
        if formulary2.is_valid():
            nueva_serie = Series(
                name=formulary2.cleaned_data['name'],
                season=formulary2.cleaned_data['season'],
                chapter=formulary2.cleaned_data['chapter'],
                user=request.user,
                image=formulary2.cleaned_data['image'],
            )
            nueva_serie.save()
            messages.success(request, 'Añadido con éxito')
            return redirect(to='mainpage:inicio')
    return render(request, 'mainpage/add.html', data)


@login_required(login_url=reverse_lazy('login:mainlogin'))
def delete_serie(request, pk):
    serie = Series.objects.get(id=pk)
    if request.method == 'POST':
        serie.delete()
        messages.success(request, "Eliminado con éxito")
        return redirect(to='mainpage:inicio')
    return render(request, 'mainpage/delete.html', {'serie': serie})


@login_required(login_url=reverse_lazy('login:mainlogin'))
def edit_serie(request, pk):
    serie = Series.objects.get(id=pk)
    data = {
        'Serieform': AddSerie(),
        'name': serie.name,
        'chapter': serie.chapter,
        'season': serie.season,
    }
    if request.method == 'POST':
        formulary = AddSerie(request.POST)
        if formulary.is_valid():
            nueva_serie = Series(
                name=formulary.cleaned_data['name'],
                season=formulary.cleaned_data['season'],
                chapter=formulary.cleaned_data['chapter'],
                user=request.user,
                id=serie.id,
                image=serie.image
            )
            nueva_serie.save()
            messages.success(request, "Serie modificada con éxito.")
        return redirect(to='mainpage:inicio')
    return render(request, 'mainpage/edit_serie.html', data)


@login_required(login_url=reverse_lazy('login:mainlogin'))
def delete_film(request, pk):
    film = Films.objects.get(id=pk)
    if request.method == 'POST':
        film.delete()
        messages.success(request, "Eliminado con éxito")
        return redirect(to='mainpage:inicio')
    return render(request, 'mainpage/delete.html', {'film': film})


@login_required(login_url=reverse_lazy('login:mainlogin'))
def edit_film(request, pk):
    film = Films.objects.get(id=pk)
    data = {
        'Filmform': AddFilm(),
        'name': film.name,
        'time': film.time,
        'film': film.image
    }
    if request.method == 'POST':
        formulary = AddFilm(request.POST)
        if formulary.is_valid():
            nueva_peli = Films(
                name=formulary.cleaned_data['name'],
                time=formulary.cleaned_data['time'],
                user=request.user,
                id=film.id,
                image=film.image,
            )
            nueva_peli.save()
            messages.success(request, 'Pelicula modificada con éxito')
        return redirect(to='mainpage:inicio')
    return render(request, 'mainpage/edit_film.html', data)


@login_required(login_url=reverse_lazy('login:mainlogin'))
def fetch(request):
    # Aqui trabajaremos con la api de IMDB por lo que hago el parametro global
    global data
    if request.method == 'POST':
        # el modelo Fetch es auxiliar por lo que cada vez que se carga la pagina se elimina
        Fetch.objects.all().delete()

        # recojo el titulo introducido
        keyword = request.POST.get('title')
        # search es el metodo de la api imdb.py
        json = search(keyword)

        # si se devuelven resultados
        if json['Response'] != "False":
            resultset = json['Search']
            # recorro los resultados y los añado a la tabla Fetch
            for result in resultset:
                variable = Fetch(
                    title=result['Title'],
                    image=result['Poster'],
                    imdb=result['imdbID'],
                    type=result['Type']
                )
                variable.save()
                total = Fetch.objects.all()
                data = {
                    'keyword': keyword,
                    'fetch': total
                }
            return render(request, 'mainpage/fetch.html', data)
        else:
            # en el caso de que la api no encuentre nada, mando este mensaje
            data = {'message': "No se han encontrado resultados para: ", 'keyword': keyword}
            return render(request, 'mainpage/fetch.html', data)
    # este return es para cuando el request:method = GET, va sin parametros
    return render(request, 'mainpage/fetch.html')


@login_required(login_url=reverse_lazy('login:mainlogin'))
def save_fetch(request, pk):
    # saco todos los datos de la pelicula/serie elegida y compruebo su tipo de contenido
    json = search_by_id(pk)

    if json['Type'] == "movie":
        nueva_peli = Films(
            name=json['Title'],
            user=request.user,
            image=json['Poster']
        )
        nueva_peli.save()
        messages.success(request, 'HAS AÑADIDO LA PELÍCULA CORRECTAMENTE')
        return redirect(to='mainpage:inicio')

    if json['Type'] == "series":
        nueva_serie = Series(
            name=json['Title'],
            user=request.user,
            image=json['Poster'],
        )
        nueva_serie.save()
        messages.success(request, 'HAS AÑADIDO LA SERIE CORRECTAMENTE')
        return redirect(to='mainpage:inicio')
    messages.error(request, 'NO SE HA PODIDO AÑADIR')
    return redirect(to='mainpage:inicio')


@login_required(login_url=reverse_lazy('login:mainlogin'))
def add_note(request):
    if request.method == 'POST':
        nueva_nota = NewNote(request.POST)

        if nueva_nota.is_valid():
            id_nota = nueva_nota.cleaned_data['id_nota']
            nota = nueva_nota.cleaned_data['nota_text']
            type = nueva_nota.cleaned_data['type_nota']

            if type == 'serie':
                serie = Series.objects.get(id=id_nota)
                serie.nota = nota
                serie.save()
                messages.success(request, 'Nota añadida con éxito')

            if type == 'pelicula':
                film = Films.objects.get(id=id_nota)
                film.nota = nota
                film.save()
                messages.success(request, 'Nota añadida con éxito')

    return redirect(to='mainpage:inicio')


@login_required(login_url=reverse_lazy('login:mainlogin'))
def change_username(request):
    if request.method == 'POST':
        form = UsernameForm(request.POST)
        if form.is_valid():
            newusername = form.cleaned_data['username']
            user = User.objects.get(username=request.user.username)
            user.username = newusername
            user.save()
            messages.success(request, 'Nombre de usuario actualizado con éxito')
        else:
            messages.error(request, 'El nombre de usuario ya está en uso.')
    return redirect(to='mainpage:perfil')


@login_required(login_url=reverse_lazy('login:mainlogin'))
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'La contraseña se ha cambiado con éxito!')
            return redirect(to='mainpage:perfil')
        else:

mysite/templates/mainpage/delete.html
{% extends 'mainpage/mainpage_base.html' %}
{% block title %}
    Eliminar Registro
{% endblock %}
{% block content %}

<div class="container">

        <section class="intro">
            <div class="column">
                <form method="post">
                    {% csrf_token %}
                    <h1>¿Desea eliminar {{ serie.name }} {{ film.name }}?</h1>
                    <div style="text-align: center; margin-top: 2%">
                        <button style="margin-right: 1%" type="submit" class="button is-primary is-inverted is-rounded">CONFIRMAR</button>
                        <a class="button is-danger is-rounded is-inverted" href="{% url 'mainpage:inicio' %}">Volver a Inicio</a>
                    </div>
                </form>
             </div>
    </section>
</div>

{% endblock %}

mysite/templates/mainpage/edit.html
{% extends 'mainpage/mainpage_base.html' %}
{% load static %}
{% block title %}
    Añade una Serie
{% endblock %}

{% block content %}
    <div class="container" style="background-color: #00d1b2; padding-bottom: 1px">
        <div class="columns is-mobile" style="margin-bottom: 10%; margin-top: 30px">
            <div class="column is-half is-offset-one-quarter" style="margin-top: 50px">
                <h3 class="title is-size-3" style="text-align: center; color: rgb(0, 0, 0)">¿HAS VISTO NUEVOS CAPÍTULOS? ANÓTALO AQUI DEBAJO</h3>
                 <form name="f1" id="f1" method="post" enctype="multipart/form-data">

                    {% csrf_token %}

                        <div class="field"><label>Título</label>
                            <input type="text" name="name" class="input" placeholder="Título" id="id_name" value="{{name}}">
                        </div>
                        <div class="field"><label>Plataforma</label>
                            <input type="text" name="platform" class="input" placeholder="Plataforma" id="id_platform" value="{{platform}}">
                        </div>
                        <div class="field"><label>Capítulo</label>
                            <input type="text" name="chapter" class="input" placeholder="Capítulo" id="id_chapter" value="{{chapter}}">
                        </div>
                        <div class="field"><label>Temporada</label>
                            <input type="text" name="season" class="input" placeholder="Temporada" id="id_season" value="{{season}}">
                        </div>
                     <br/>
                     <button type="submit" class="button is-large is-fullwidth">Confirmar Cambios</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

mysite/templates/mainpage/perfil.html
{% extends 'mainpage/mainpage_base.html' %}
{% load static %}
{% block title %}
    Perfil de Usuario
{% endblock %}

{% block content %}
    <section class="intro">
        {% if messages %}
            {% for message in messages %}
            <div class="message1" style="position: absolute; width: 100%">
                <article class="message is-primary is-inverted">
                    <div class="message-body">{{ message }}</div>
                </article></div>
            {% endfor %}
        {% endif %}
        <br/>
        <div class="column">
            <h1>{{ user.username.upper }}</h1>
            <h3>ESTE ES TU PERFIL DE USUARIO, USANDO EL BOTÓN DE ABAJO PUEDES MODIFICAR LOS DATOS</h3>
        </div>

        <!--imagen del usuario-->
        <div class="columns is-mobile" style="margin: 1% 20% 0;">
            {% if image %}
            <figure class="image">
                <img class="is-rounded" style="min-width: 226px; max-width: 230px; min-height: 226px; max-height: 230px "
                     src="/{{ image.image }}" alt="profile image">
            </figure>
            {% else %}
            <figure class="image">
                <img class="" src="/static/media/default.png" alt="profile image">
            </figure>
            {% endif %}

        <!--formulario para cambiar datos del usuario-->
         <form name="f1" id="f1" method="post" enctype="multipart/form-data" style="margin-left: 5%; width: 100%">
             {% csrf_token %}
             <div class="field"><label for="id_first_name">Nombre</label>
                <input type="text" name="first_name" class="input" placeholder="Nombre" id="id_first_name"
                       disabled value="{{user.first_name}}">
            </div>
            <div class="field"><label for="id_last_name">Apellidos</label>
                <input type="text" name="last_name" class="input" placeholder="Apellidos" id="id_last_name"
                       disabled value="{{user.last_name}}">
            </div>
            <div class="field"><label for="id_email">Correo Electrónico</label>
                <input type="text" name="email" class="input" placeholder="Correo Electrónico"
                       disabled id="id_email" value="{{user.email}}">
            </div>

            <br/>
             <div style="text-align: right">
                 <a id="cancel" class="button is-danger is-inverted is-rounded" href="{% url 'mainpage:perfil' %}"
                 style="display:none">
                     Cancelar
                 </a>
                 <button id='save' class="button is-primary is-inverted is-rounded" type="submit" style="display: none">
                     Guardar Cambios
                 </button>
            </div>
        </form>
        </div>
        <div style="text-align: right; margin-right: 20%">
            <button id='editor' class="button is-primary is-inverted is-rounded" onclick="toggle()">EDITAR</button>
        </div>

        <div style="text-align: center; margin-top: 2%">
            <button class="button is-warning is-light" onclick="modalimageTrigger()"
                    style="width: 30%; min-width: 220px">Cambiar Foto de Perfil</button>

            <button class="button is-warning is-light" onclick="modalTrigger()"
                    style="margin: 0 2% 0; width: 30%; min-width: 220px">Cambiar Nombre de Usuario</button>

            <button class="button is-warning is-light" onclick="modalpasswordTrigger()"
                    style="width: 30%; min-width: 220px">Cambiar Contraseña</button>
        </div>

</section>

<!--Bulma modal for username-->
<div class="modal" id="modal">
  <div class="modal-background" onclick="modalTrigger()"></div>
  <div class="modal-content">
      <div class="modal-content">
            <div class="modal-card">
                <header class="modal-card-head" style="background-color: #00d1b2">
                    <img alt="logo" src="/static/media/LogoAleAPrisa.png" style="height: 60px !important">
                    <h1 class="modal-card-title" style="padding-left: 2%"><strong style="color: white">
                        Cambiar Nombre de Usuario</strong>
                    </h1>
                    <button id="close_comment_modal" class="delete" aria-label="close"
                            onclick="modalTrigger()"></button>
                </header>

                <form method="post" action="{% url 'mainpage:cambiar user' %}">
                    {% csrf_token %}
                    <section class="modal-card-body">
                        <div class="columns is-centered">
                            <div class="column has-text-centered">
                                <div class="field">
                                    <label for="id_username" style=" font-weight: bold; color: grey">
                                        NOMBRE DE USUARIO ACTUAL: {{user.username.upper}}
                                    </label>
                                    <input type="text" name="username" class="input" placeholder="Nombre de Usuario"
                                           id="id_username" value="{{user.username}}" style="margin-top: 2%">
                                </div>
                            </div>
                        </div>

                    </section>
                    <footer class="modal-card-foot" style="background-color: #00d1b2">
                        <button type="submit" class="button is-primary is-rounded is-inverted">Guardar</button>
                        <button class="button is-danger is-rounded is-inverted" type="button" onclick="modalTrigger()">
                            Cancelar
                        </button>
                    </footer>
                </form>
            </div>
      </div>
  </div>
</div>


<!--Bulma modal for password-->
<div class="modal" id="modalpassword">
  <div class="modal-background" onclick="modalpasswordTrigger()"></div>
  <div class="modal-content">
      <div class="modal-content">
            <div class="modal-card">
                <header class="modal-card-head" style="background-color: #00d1b2">
                    <img alt="logo" src="/static/media/LogoAleAPrisa.png" style="height: 60px !important">
                    <h1 class="modal-card-title" style="padding-left: 2%"><strong style="color: white">
                        Cambiar Contraseña</strong>
                    </h1>
                    <button id="close_modal" class="delete" aria-label="close"
                            onclick="modalpasswordTrigger()"></button>
                </header>

                <form method="post" action="{% url 'mainpage:update password' %}">
                    {% csrf_token %}
                    <section class="modal-card-body">
                        <p style="color: grey">La nueva contraseña debe tener al menos 8 carácteres y un número</p>
                        <div class="columns is-centered">
                            <div class="column has-text-centered">
                                <div class="field">
                                    <label for="id_old_password" style=" font-weight: bold; color: grey">
                                    </label>
                                    <input type="password" name="old_password" class="input" placeholder="Contraseña Actual"
                                           id="id_old_password"  style="margin-top: 2%">

                                    <label for="id_new_password1" style=" font-weight: bold; color: grey">
                                    </label>
                                    <input type="password" name="new_password1" class="input" placeholder="Nueva Contraseña"
                                           id="id_new_password1"  style="margin-top: 2%">

                                    <label for="id_new_password2" style=" font-weight: bold; color: grey">
                                    </label>
                                    <input type="password" name="new_password2" class="input" placeholder="Confirmar Nueva Contraseña"
                                           id="id_new_password2"  style="margin-top: 2%">
                                </div>
                            </div>
                        </div>

                    </section>
                    <footer class="modal-card-foot" style="background-color: #00d1b2">
                        <button type="submit" class="button is-primary is-rounded is-inverted">Guardar</button>
                        <button class="button is-danger is-rounded is-inverted" type="button" onclick="modalpasswordTrigger()">
                            Cancelar
                        </button>
                    </footer>
                </form>
            </div>
      </div>
  </div>
</div>

<!--Bulma modal for image-->
<div class="modal" id="modalimage">
  <div class="modal-background" onclick="modalimageTrigger()"></div>
  <div class="modal-content">
      <div class="modal-content">
            <div class="modal-card">
                <header class="modal-card-head" style="background-color: #00d1b2">
                    <img alt="logo" src="/static/media/LogoAleAPrisa.png" style="height: 60px !important">
                    <h1 class="modal-card-title" style="padding-left: 2%"><strong style="color: white">
                        Cambiar Foto de Perfil</strong>
                    </h1>
                    <button id="close_image_modal" class="delete" aria-label="close"
                            onclick="modalimageTrigger()"></button>
                </header>

                <form method="post" action="{% url 'mainpage:set image' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <section class="modal-card-body">
                        <div class="columns is-centered">
                            <div class="column has-text-centered">
                                <div class="field">
                                    <label  for="id_image"></label>
                                    <input class="file-label" type="file" name="image" id="id_image" style="margin-top: 2%">
                                </div>
                            </div>
                        </div>

                    </section>
                    <footer class="modal-card-foot" style="background-color: #00d1b2">
                        <button type="submit" class="button is-primary is-rounded is-inverted">Guardar</button>
                        <button class="button is-danger is-rounded is-inverted" type="button" onclick="modalimageTrigger()">
                            Cancelar
                        </button>
                    </footer>
                </form>
            </div>
      </div>
  </div>
</div>

<script src="{% static 'js/perfil.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.2.1.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
    setTimeout(function() {
     $(".message1").fadeOut(1500);
      },4000);
});
</script>

{% endblock %}